import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import Sidebar from "../components/sidebar";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="flex">
        <Sidebar />

        <main className={styles.main2}>
          <div className="flex flex-col">
            <p className="text-gray-400 ml-5 py-3">Home</p>
            <p className="text-xl ml-5">履歴</p>
            <table className="border-collapse border-2 border-gray-600 mx-5 w-full rounded-md">
              <thead>
                <tr>
                  <th className="border px-4 py-2">日付</th>
                  <th className="border px-4 py-2">ユーザー</th>
                  <th className="border px-4 py-2">内容</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border px-4 py-2">2022/04/07</td>
                  <td className="border px-4 py-2">user1</td>
                  <td className="border px-4 py-2">ユーザーを作成しました</td>
                </tr>
                <tr>
                  <td className="border px-4 py-2">2022/04/08</td>
                  <td className="border px-4 py-2">user2</td>
                  <td className="border px-4 py-2">ユーザーを作成しました</td>
                </tr>
                <tr>
                  <td className="border px-4 py-2">2022/04/09</td>
                  <td className="border px-4 py-2">user3</td>
                  <td className="border px-4 py-2">ユーザーを作成しました</td>
                </tr>
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>
  );
};

export default Home;
