import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../src/components/header.js";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <p>履歴</p>
        <table className="table-auto">
          <thead>
            <tr>
              <th className="px-4 py-2">日付</th>
              <th className="px-4 py-2">ユーザー</th>
              <th className="px-4 py-2">内容</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="border px-4 py-2">2022/04/07</td>
              <td className="border px-4 py-2">user1</td>
              <td className="border px-4 py-2">ユーザーを作成しました。</td>
            </tr>
            <tr>
              <td className="border px-4 py-2">2022/04/08</td>
              <td className="border px-4 py-2">user2</td>
              <td className="border px-4 py-2">ユーザーを作成しました</td>
            </tr>
            <tr>
              <td className="border px-4 py-2">2022/04/09</td>
              <td className="border px-4 py-2">user3</td>
              <td className="border px-4 py-2">ユーザーを作成しました</td>
            </tr>
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default Home;
