import Link from "next/link";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { useState } from "react";

export default function Index() {
  const router = useRouter();
  const [input, loginInput] = useState<string>();
  const clickButton = () => {
    if (!input) return;
    localStorage.setItem("login_id", input);
    router.push({
      pathname: "/home",
      query: { input: input },
    });
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="flex flex-col bg-white rounded-md py-6">
          <div className="text-center py-2">
            <p className="text-3xl">ログイン</p>
          </div>
          <div className="text-center px-10">
            <form>
              <input
                type="text"
                value={input}
                onChange={(e) => loginInput(e.target.value)}
                className="text-center border border-gray-800 rounded-md py-1 px-5 my-2 placeholder-gray-300"
                placeholder="メールアドレス"
              />
            </form>
            <form>
              <input
                className="text-center border border-gray-800 rounded-md py-1 px-5 my-2 placeholder-gray-300"
                placeholder="パスワード"
              />
            </form>
          </div>
          <div className="text-center py-2">
            <button
              onClick={clickButton}
              className="px-3 py-2 bg-red-500 text-lg text-white rounded-full"
            >
              ログイン
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
