import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import Sidebar from "../components/sidebar";

const User = () => {
  const data = [
    {
      id: "id_1",
      name: "user1",
      email: "user1@com",
      genre: "管理者",
    },
    {
      id: "id_2",
      name: "user2",
      email: "user2@com",
      genre: "ユーザー",
    },
    {
      id: "id_3",
      name: "user3",
      email: "user3@com",
      genre: "ユーザー",
    },
  ];

  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <div className="flex">
          <Sidebar />
          <main className={styles.main2}>
            <div className="flex-col">
              <p className="text-gray-400 ml-5 py-3">履歴</p>
              <p className="text-xl ml-5">検索</p>
              <div className="flex justify-center">
                <div>
                  <p>id</p>
                  <input className="text-center mx-2 border border-gray-800 rounded-md py-1 px-1 my-2" />
                </div>
                <div>
                  <p>名前</p>
                  <input className="text-center m-2 border border-gray-800 rounded-md py-1 px-1 my-2" />
                </div>
                <div>
                  <p>メールアドレス</p>
                  <input className="text-center m-2 border border-gray-800 rounded-md py-1 px-1 my-2" />
                </div>
                <div>
                  <p>権限</p>
                  <input className="text-center m-2 border border-gray-800 rounded-md py-1 px-1 my-2" />
                </div>
              </div>
            </div>
            <button className="m-2 px-5 py-2 bg-red-500 text-lg text-white rounded-full">
              検索
            </button>
            <table className="table-auto">
              <thead>
                <tr>
                  <th className="px-4 py-2">id</th>
                  <th className="px-4 py-2">名前</th>
                  <th className="px-4 py-2">メールアドレス</th>
                  <th className="px-4 py-2">権限</th>
                </tr>
              </thead>
              <tbody>
                {data.map((value, key) => {
                  return (
                    <tr key={key}>
                      <td className="border px-4 py-2">{value.id}</td>
                      <td className="border px-4 py-2">{value.name}</td>
                      <td className="border px-4 py-2">{value.email}</td>
                      <td className="border px-4 py-2">{value.genre}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </main>
        </div>
      </div>
    </>
  );
};

export default User;
