import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

export default function Header() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-white h-12 border-2 border-gray-600 rounded-sm text-gray-600">
        <div className="pt-2 px-2 text-right">
          {"こんにちは！  " + localStorage.getItem("login_id") + "  さん"}
        </div>
      </header>
    </>
  );
}
